const techIcons: { [key: string]: string } = {
  React: "/techIcons/react/react-original.svg",
  "Next.js": "/techIcons/nextjs/nextjs-original.svg",
  TypeScript: "/techIcons/typescript/typescript-original.svg",
  JavaScript: "/techIcons/javascript/javascript-original.svg",
  HTML5: "/techIcons/html5/html5-original.svg",
  CSS3: "/techIcons/css3/css3-original.svg",
  "Tailwind CSS": "/techIcons/tailwindcss/tailwindcss-original.svg",
  "Material UI": "/techIcons/materialui/materialui-original.svg",
  "Node.js": "/techIcons/nodejs/nodejs-original.svg",
  Express: "/techIcons/express/express-original.svg",
  PostgreSQL: "/techIcons/postgresql/postgresql-original.svg",
  Prisma: "/techIcons/prisma/prisma-original.svg",
  Docker: "/techIcons/docker/docker-original.svg",
  Git: "/techIcons/git/git-original.svg",
  GitHub: "/techIcons/github/github-original.svg",
  "GitHub Actions": "/techIcons/githubactions/githubactions-original.svg",
  Vercel: "/techIcons/vercel/vercel-original.svg",
  Cloudflare: "/techIcons/cloudflare/cloudflare-original.svg",
  ESLint: "/techIcons/eslint/eslint-original.svg",
  Jest: "/techIcons/jest/jest-plain.svg",
  Puppeteer: "/techIcons/puppeteer/puppeteer-original.svg",
  Postman: "/techIcons/postman/postman-original.svg",
  Figma: "/techIcons/figma/figma-original.svg",
  "VS Code": "/techIcons/vscode/vscode-original.svg",
  npm: "/techIcons/npm/npm-original-wordmark.svg",
  pnpm: "/techIcons/pnpm/pnpm-original.svg",
  Webpack: "/techIcons/webpack/webpack-original.svg",
  Nodemon: "/techIcons/nodemon/nodemon-original.svg",
  JSON: "/techIcons/json/json-original.svg",
  YAML: "/techIcons/yaml/yaml-original.svg",
  SSH: "/techIcons/ssh/ssh-original.svg",
  "Raspberry Pi": "/techIcons/raspberrypi/raspberrypi-original.svg",
  OAuth: "/techIcons/oauth/oauth-original.svg",
  Notion: "/techIcons/notion/notion-original.svg",
  LinkedIn: "/techIcons/linkedin/linkedin-original.svg",
  LeetCode: "/techIcons/leetcode/leetcode-original.svg",
  Google: "/techIcons/google/google-original.svg",
  Chrome: "/techIcons/chrome/chrome-original.svg",
  Apple: "/techIcons/apple/apple-original.svg",
};

export function getTechStackIcon(tech: string): string {
  return techIcons[tech] || "/techIcons/default.svg";
}
